# Generated by Django 5.1.6 on 2025-02-24 02:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_internet'),
    ]

    operations = [
        migrations.AddField(
            model_name='internet',
            name='unique_id',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='unique_id',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
