# Generated by Django 5.1.6 on 2025-02-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_internet_unique_id_location_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internet',
            name='unique_id',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='location',
            name='unique_id',
            field=models.IntegerField(default=100000),
        ),
    ]
